name: 'kubectl - with aws cli support'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Yucel Okcu <yucel.n.okcu@gmail.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  args:
    description: 'Arguments for the CLI command'
    required: false
  redirect-to:
    description: 'Variable name to redirect CLI output'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    dest: ${{ inputs.redirect-to }}
